# .github/workflows/sample-workflow.yml
name: Sample Workflow # Name for your workflow (optional)

on: 
  push:
    branches: 
      - main    # Run this workflow on pushes to the 'main' branch
  pull_request: # Also trigger on pull requests

jobs:
  build:
    runs-on: ubuntu-latest # Specify OS for this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Step using a GitHub Action to check out the repo code

      - name: Run a script
        run: echo "Hello, GitHub Actions!" # Custom shell command
